# Generated by Django 3.2 on 2021-06-23 15:11

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('desc', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Расходный материал',
                'verbose_name_plural': 'Расходные материалы',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100, verbose_name='Обозначение')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('desc', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
                ('consumables', models.ManyToManyField(blank=True, related_name='parts_cons', to='catalog.Consumable', verbose_name='Связанные расходные материалы')),
            ],
            options={
                'verbose_name': 'Деталь',
                'verbose_name_plural': 'Детали',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100, verbose_name='Обозначение')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('desc', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
                ('consumables', models.ManyToManyField(blank=True, related_name='units_cons', to='catalog.Consumable', verbose_name='Связанные расходники')),
                ('parts', models.ManyToManyField(blank=True, related_name='units_parts', to='catalog.Part', verbose_name='Связанные запчасти')),
            ],
            options={
                'verbose_name': 'Узел',
                'verbose_name_plural': 'Узлы',
            },
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100, verbose_name='Обозначение')),
                ('desc', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
                ('consumables', models.ManyToManyField(blank=True, related_name='bodies_cons', to='catalog.Consumable', verbose_name='Связанные расходники')),
                ('parts', models.ManyToManyField(blank=True, related_name='bodies_parts', to='catalog.Part', verbose_name='Связанные запчасти')),
                ('units', models.ManyToManyField(blank=True, related_name='bodies_units', to='catalog.Unit', verbose_name='Связанные узлы')),
            ],
            options={
                'verbose_name': 'Кузов',
                'verbose_name_plural': 'Кузова',
            },
        ),
    ]
