# Generated by Django 3.2 on 2021-06-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='units_set', to='catalog.Unit', verbose_name='Связанные узлы'),
        ),
    ]
