# Generated by Django 3.2 on 2021-06-23 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_unittype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalog.unittype', verbose_name='Тип узла'),
            preserve_default=False,
        ),
    ]
