# Generated by Django 3.2 on 2021-06-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='_catalog_unit_units_+', to='catalog.Unit', verbose_name='Связанные узлы'),
        ),
    ]
