# Generated by Django 3.2 on 2021-06-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='units',
            field=models.ManyToManyField(blank=True, to='catalog.Unit'),
        ),
    ]
