# Generated by Django 3.2 on 2021-06-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_part_units'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supplies',
            new_name='Consumable',
        ),
        migrations.RemoveField(
            model_name='part',
            name='units',
        ),
        migrations.AddField(
            model_name='unit',
            name='consumables',
            field=models.ManyToManyField(blank=True, to='catalog.Consumable', verbose_name='Связанные расходники'),
        ),
        migrations.AddField(
            model_name='unit',
            name='parts',
            field=models.ManyToManyField(blank=True, to='catalog.Part', verbose_name='Связанные запчасти'),
        ),
    ]
