# Generated by Django 3.2 on 2021-06-22 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210623_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumable',
            name='designation',
        ),
    ]
