# Generated by Django 3.2 on 2021-05-09 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_router_specifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='router',
            old_name='specifications',
            new_name='file',
        ),
    ]
