# Generated by Django 3.2 on 2021-06-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_consumable_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='consumables',
            field=models.ManyToManyField(blank=True, related_name='units', to='catalog.Consumable', verbose_name='Связанные расходники'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='parts',
            field=models.ManyToManyField(blank=True, related_name='units', to='catalog.Part', verbose_name='Связанные запчасти'),
        ),
    ]
