# Generated by Django 3.2 on 2021-05-10 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_specifications_router_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Router',
        ),
    ]
