# Generated by Django 3.2 on 2021-06-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210623_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='consumables',
            field=models.ManyToManyField(blank=True, to='catalog.Consumable', verbose_name='Связанные расходники'),
        ),
    ]
