# Generated by Django 3.2 on 2021-06-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_unit_consumables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='consumables',
            field=models.ManyToManyField(blank=True, related_name='units_cons', to='catalog.Consumable', verbose_name='Связанные расходники'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='parts',
            field=models.ManyToManyField(blank=True, related_name='units_parts', to='catalog.Part', verbose_name='Связанные запчасти'),
        ),
    ]
