# Generated by Django 3.2 on 2021-06-22 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_part_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='units',
        ),
    ]
