# Generated by Django 3.2 on 2021-04-23 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0003_auto_20210423_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subsection',
            old_name='chapter',
            new_name='section',
        ),
    ]
