# Generated by Django 3.2 on 2021-04-23 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0004_rename_chapter_subsection_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='creation_date',
        ),
    ]
