# Generated by Django 3.2 on 2021-04-23 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0005_remove_book_creation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_open',
            new_name='published',
        ),
    ]
